services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"   # dashboard do Eureka (opcional em produção)
    networks:
      - lancheria-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  lancheria-app:
    build: ./lancheria-app
    container_name: lancheria-app
    networks:
      - lancheria-net
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  estoque:
    build: ./servico-estoque
    container_name: estoque
    networks:
      - lancheria-net
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"   # único ponto de entrada externo
    networks:
      - lancheria-net
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

networks:
  lancheria-net:
    driver: bridge
